### ISSUE TITLE
HeaveyMetal Dosent Work In Blast Furnace

### ISSUE THREAD

**Issue by Morpheus1101** [swolewizard/EpicValheimAdditions#21]
We got Heavymetal to drop thanks to using GoldenJudes Minshaft mod...however idk if its the Hildir update, but i cant get the ore to smelt in the blast Furnace, so im having to use the Frometal BattleAxe to chop down the Tree's in the Ashlands.

**Comment by swolewizard** [comment]
Make sure the **'Huntard.EpicValheimsAdditions_Content.json'** has Mistlands toggled **'true'**, in the **'\BepInEx\config'** folder, like so:

[
    {
        "Description" : "Locations contain (Altars/Bosses/Vegvisirs/Ores/Trees), Mistlands/Deepnorth/Ashlands contain (Weapons/Tools/Resources/Crafting tables/Boss summons). Having just the locations toggled true, wouldn't work progression wise.",
        "MistlandsLocations" : true,
        "Mistlands"          : true,
        "DeepNorthLocations" : true,
        "DeepNorth"          : true,
        "AshlandsLocations"  : true,
        "Ashlands"           : true
    }
]

**Comment by Morpheus1101** [comment]
We have this set to true an unfortunately it still won't allow it to be placed into the Blast Furnace

**Comment by swolewizard** [comment]
I have conducted testing with only my mod installed and can confirm that it functions as intended. Specifically, OreHeavymetal can be successfully smelted in the blast furnace.

Given your reference to "we," I assume you are playing in a multiplayer environment. This information is crucial for troubleshooting this issue. Therefore, please ensure that both you (the client) and the server, along with all other players connecting to it, have their Mistlands & MistlandsLocations settings set to 'true.' It's worth noting that the code responsible for enabling the ore to be smelted in the blast furnace is only activated when Mistlands is set to 'true.'

If you have verified that all users and the server have correctly configured these settings to 'true' and the problem persists, it is possible that another mod is causing a conflict, disrupting the interaction between the ore and the blast furnace. I want to clarify that my primary concern is ensuring the proper functionality of my mod. Any issues caused by other mods are beyond my scope of responsibility.

![working](https://i.imgur.com/ZfzdHcH.jpg)
![working](https://i.imgur.com/6Lac0os.jpg)
![working](https://i.imgur.com/AEQuFo8.jpg)

**Comment by Morpheus1101** [comment]
yes it is on a Multiplayer Dedicated server.  I believe its something to do with mod interaction since it works perfectly for you as intended. thanks for your time on this.
