### ISSUE TITLE
Flametal is using the standard forge

### ISSUE THREAD

**Issue by TitanHansen** [swolewizard/EpicValheimAdditions#27]
Hi, thank you for a great mod, really appreciate it. The flametal weapons is using the normal forge and not Thors forge, is this intended?

**Comment by swolewizard** [comment]
This might occur because you're using a modpack that alters the crafting locations of items. You can check the source code on this GitHub, and it will confirm that it is correctly coded to be crafted at Thor's Forge.

https://github.com/swolewizard/EpicValheimAdditions/blob/8c1af5509fdfcc159133953a459d9c13ea44332f/EpicValheimAdditions.cs#L2227
